FROM ubuntu:artful

# Setup http://locust.io

RUN ulimit -c -m -s -t unlimited && apt-get update && apt-get install -y build-essential libncursesw5-dev libreadline-dev libssl-dev libgdbm-dev libc6-dev libsqlite3-dev libxml2-dev libxslt-dev python python-dev python-setuptools python-pip && apt-get clean && apt-get autoclean && apt-get remove; pip install locustio; pip install pyzmq; pip install beautifulsoup4; mkdir -p /load/scripts

COPY ./scripts/* /load/scripts/
ENV LOCUST_FILE /load/scripts/locustfile.py
RUN chmod 755 /load/scripts/*

EXPOSE 8089 5557 5558
CMD ["/load/scripts/run.sh"]